ALTER TABLE ORDERT DROP FOREIGN KEY FK_ORDER_REG;
ALTER TABLE FEEDBACK DROP FOREIGN KEY FK_FB_REG;
ALTER TABLE LOGIN DROP FOREIGN KEY FK_LOGIN_REG;
ALTER TABLE PROCOMMENT DROP FOREIGN KEY FK_PC_REG;

DROP INDEX R_UID ON REGISTRATION;
DROP INDEX O_UID ON ORDERT;
DROP INDEX F_UID ON FEEDBACK;
DROP INDEX L_UID ON LOGIN;
DROP INDEX PC_UID ON PROCOMMENT;

DROP TABLE REGISTRATION; 
DROP TABLE LOGIN;
DROP TABLE PRODUCT;
DROP TABLE ORDERT;
DROP TABLE FEEDBACK; 
DROP TABLE ADMIN;
DROP TABLE NEWS;
DROP TABLE PROCOMMENT;


CREATE TABLE REGISTRATION ( 
	REGISTRATIONID			BIGINT PRIMARY KEY AUTO_INCREMENT,
	USERID							VARCHAR( 50 ) UNIQUE NOT NULL,
	CUSTOMERNAME		VARCHAR( 50 ) NOT NULL,
	GENDER							CHAR( 1 ),
	SECURITYQUESTION	VARCHAR( 100 ) NOT NULL,
	SECURITYANSWER		VARCHAR( 50 ) NOT NULL,	
	PHONENUMBER			BIGINT( 11 ) NOT NULL,	
	EMAILADDRESS			VARCHAR(50) ,
	ADDRESS						VARCHAR( 200 ) NOT NULL,	
	DATEOFREGIST				DATE NOT NULL,
	CERTIFICATION				CHAR(1) NOT NULL,
	DATEOFBIRTH				DATE,
    INDEX R_UID(USERID)
 )ENGINE=INNODB  AUTO_INCREMENT=10000000 DEFAULT CHARSET=utf8;
 
 CREATE TABLE LOGIN(
	USERID					VARCHAR( 50 ) PRIMARY KEY,
	`PASSWORD`			VARCHAR( 25 ) NOT NULL,
	`STATUS`					CHAR(10) NOT NULL,
	  INDEX L_UID(USERID),
 	CONSTRAINT FK_LOGIN_REG FOREIGN KEY (USERID) REFERENCES REGISTRATION(USERID)
    ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=INNODB;
  
CREATE TABLE PRODUCT(
 	PROID						INT PRIMARY KEY AUTO_INCREMENT,
 	PRONAME				VARCHAR(50) NOT NULL,
 	PROCATEGORY		VARCHAR(10) NOT NULL,
 	PROPRICE				DOUBLE NOT NULL,
 	IMGURL					VARCHAR(100)  NOT NULL,
 	PRODES					VARCHAR(100),
 	PROLINK				VARCHAR(200),
 	SELLEDDATE			DATE
 )ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;
 
 CREATE TABLE ORDERT(
 	ORDERID				INT PRIMARY KEY AUTO_INCREMENT,
 	USERID					VARCHAR( 50 ) NOT NULL, 				
 	PRODUCTS			VARCHAR(200) NOT NULL,
 	TOTONUM			INT NOT NULL,
 	TOTALPRICE			DOUBLE NOT NULL,
 	ORDERTIME			DATE NOT NULL,
 	`STATUS`					CHAR(10),
    INDEX O_UID(USERID),
 	CONSTRAINT FK_ORDER_REG FOREIGN KEY (USERID) REFERENCES REGISTRATION(USERID)
    ON DELETE RESTRICT ON UPDATE CASCADE
 )ENGINE=INNODB  AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;

CREATE TABLE FEEDBACK ( 
	FEEDBACKID						INT  PRIMARY KEY AUTO_INCREMENT ,
	FEEDBACKCOMMENT		VARCHAR( 1000 ) NOT NULL,
	USERID								VARCHAR( 50 ) NOT NULL,
	INDEX F_UID(USERID),
 	CONSTRAINT FK_FB_REG FOREIGN KEY (USERID) REFERENCES REGISTRATION(USERID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;

CREATE TABLE ADMIN(
	ADMINID			VARCHAR(20) PRIMARY KEY,
	`PASSWORD`		VARCHAR(20)  NOT NULL
)ENGINE=INNODB;

CREATE TABLE NEWS(
	NEWSID					INT PRIMARY KEY AUTO_INCREMENT,
	NEWSTITLE			VARCHAR(60) NOT NULL,
	NEWSCONTENT	VARCHAR(3000) NOT NULL,
	ADDTIME				DATE NOT NULL
)ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;


CREATE TABLE PROCOMMENT(
	COMMENTID		INT PRIMARY KEY AUTO_INCREMENT,
	USERID					VARCHAR( 50 ) NOT NULL,
	`COMMENT`			VARCHAR( 300 ) NOT NULL,
	INDEX PC_UID(USERID),
 	CONSTRAINT FK_PC_REG FOREIGN KEY (USERID) REFERENCES REGISTRATION(USERID)
    ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=INNODB AUTO_INCREMENT=1000000 DEFAULT CHARSET=utf8;

COMMIT;


INSERT INTO PRODUCT(PROID,PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK,SELLEDDATE) VALUES('1','EOS 6D','照相机',13299.0,'../page-resource/img/products/EOS_6D_big.jpg','2020万像素/144.5 x 110.5 x 71.2毫米/LP-E6电池','','2016-1-1');
INSERT INTO PRODUCT(PROID,PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK,SELLEDDATE) VALUES('2','EOS 7D','照相机',9699.0,'../page-resource/img/products/EOS_7D_big.jpg','2020万像素/144.5 x 110.5 x 71.2毫米/可充电锂电池','','2016-1-1');
INSERT INTO PRODUCT(PROID,PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK,SELLEDDATE) VALUES('3','EOS 80D','照相机',7699.0,'../page-resource/img/products/EOS_80D_big.jpg','2420万像素/139 x 105.2 x 78.5毫米/LP-E6N电池','','2016-1-1');
INSERT INTO PRODUCT(PROID,PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK,SELLEDDATE) VALUES('4','EF 8-15mm f4L USM','配件',1488.0,'../page-resource/img/products/EF_8-15mm_f4L_USM_big.jpg','','','2016-1-1');
INSERT INTO PRODUCT(PROID,PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK,SELLEDDATE) VALUES('5','600EX-RT','配件',1689.0,'../page-resource/img/products/600EX-RT_big.jpg','','','2016-1-1');



INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('EOS 6D','照相机',13299.0,'../page-resource/img/products/EOS_6D_big.jpg','2020万像素/144.5 x 110.5 x 71.2毫米/LP-E6电池','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('EOS 7D','照相机',9699.0,'../page-resource/img/products/EOS_7D_big.jpg','2020万像素/144.5 x 110.5 x 71.2毫米/可充电锂电池','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('EOS 80D','照相机',7699.0,'../page-resource/img/products/EOS_80D_big.jpg','2420万像素/139 x 105.2 x 78.5毫米/LP-E6N电池','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('EF 8-15mm f4L USM','配件',1488.0,'../page-resource/img/products/EF_8-15mm_f4L_USM_big.jpg','','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('600EX-RT','配件',1689.0,'../page-resource/img/products/600EX-RT_big.jpg','','');

INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('EOS 5D MarkIII','照相机',25899,'../page-resource/img/products/EOS_5D_big.jpg.jpg','2230万像素/152.0 x 116.4 x 76.4毫米/LP-E6电池','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('LEGRIA HF G40','摄影机',8999,'../page-resource/img/products/LEGRIA_HF_G40_big.jpg','动态291万像素/	115 x 84 x 231毫米/765克/20倍光学变焦','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('LEGRIA HF R706','摄影机',2399,'../page-resource/img/products/LEGRIA_HF_R706_big.jpg','动态207万像素/53 x 58 x 116mm/240克/32倍光学变焦','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('EOS M10','照相机',2899,'../page-resource/img/products/EOS_M10_big.jpg','1800万像素/108 x 66.6 x 35毫米/LP-E12电池','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('EOS M2','照相机',2299,'../page-resource/img/products/EOS_M2_big.jpg','1800万像素/104.9 x 65.2 x 31.6毫米/LP-E12电池','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('EOS M3','照相机',3699,'../page-resource/img/products/EOS_M3_big.jpg','2420万像素/110.9 x 68 x 44.4毫米/LP-E17电池','');
INSERT INTO PRODUCT(PRONAME,PROCATEGORY,PROPRICE,IMGURL,PRODES,PROLINK) VALUES('LEGRIA mini X','摄影机',2688,'../page-resource/img/products/LEGRIA_mini_X_big.jpg','动态207万像素/82 x 30 x 109毫米/205克/单焦点/超广角镜头','');


INSERT INTO ADMIN VALUES('admin', 'admin');
INSERT INTO ADMIN VALUES('admin01', 'admin01');
INSERT INTO ADMIN VALUES('admin02', 'admin02');


COMMIT;
